//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34003.
// 
#pragma warning disable 1591

namespace HsFileTransfer.HscFile {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://www.w3.org/ns/ws-policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="hscfilesPortBinding", Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(operationResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(operation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(findHSCFileResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(findHSCFile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persistResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(persist))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getFileForProcessingResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getFileForProcessing))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(processHSCFileResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(processHSCFile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getPacketsForFile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getHSCFileResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(getHSCFile))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(markAsProcessedResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(markAsProcessed))]
    public partial class hscfilesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback operationOperationCompleted;
        
        private System.Threading.SendOrPostCallback persistOperationCompleted;
        
        private System.Threading.SendOrPostCallback processHSCFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback getHSCFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback findHSCFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFileForProcessingOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPacketsForFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback markAsProcessedOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public hscfilesService() {
            this.Url = "http://soap.hotschedules.com:8020/hsws/hscfiles";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event operationCompletedEventHandler operationCompleted;
        
        /// <remarks/>
        public event persistCompletedEventHandler persistCompleted;
        
        /// <remarks/>
        public event processHSCFileCompletedEventHandler processHSCFileCompleted;
        
        /// <remarks/>
        public event getHSCFileCompletedEventHandler getHSCFileCompleted;
        
        /// <remarks/>
        public event findHSCFileCompletedEventHandler findHSCFileCompleted;
        
        /// <remarks/>
        public event getFileForProcessingCompletedEventHandler getFileForProcessingCompleted;
        
        /// <remarks/>
        public event getPacketsForFileCompletedEventHandler getPacketsForFileCompleted;
        
        /// <remarks/>
        public event markAsProcessedCompletedEventHandler markAsProcessedCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", ResponseNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscPacket operation([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] hscPacket parameter) {
            object[] results = this.Invoke("operation", new object[] {
                        parameter});
            return ((hscPacket)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginoperation(hscPacket parameter, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("operation", new object[] {
                        parameter}, callback, asyncState);
        }
        
        /// <remarks/>
        public hscPacket Endoperation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((hscPacket)(results[0]));
        }
        
        /// <remarks/>
        public void operationAsync(hscPacket parameter) {
            this.operationAsync(parameter, null);
        }
        
        /// <remarks/>
        public void operationAsync(hscPacket parameter, object userState) {
            if ((this.operationOperationCompleted == null)) {
                this.operationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnoperationOperationCompleted);
            }
            this.InvokeAsync("operation", new object[] {
                        parameter}, this.operationOperationCompleted, userState);
        }
        
        private void OnoperationOperationCompleted(object arg) {
            if ((this.operationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.operationCompleted(this, new operationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", ResponseNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string persist([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] hscFile file) {
            object[] results = this.Invoke("persist", new object[] {
                        file});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginpersist(hscFile file, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("persist", new object[] {
                        file}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endpersist(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void persistAsync(hscFile file) {
            this.persistAsync(file, null);
        }
        
        /// <remarks/>
        public void persistAsync(hscFile file, object userState) {
            if ((this.persistOperationCompleted == null)) {
                this.persistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpersistOperationCompleted);
            }
            this.InvokeAsync("persist", new object[] {
                        file}, this.persistOperationCompleted, userState);
        }
        
        private void OnpersistOperationCompleted(object arg) {
            if ((this.persistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.persistCompleted(this, new persistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", ResponseNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object processHSCFile([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] hscFile arg0) {
            object[] results = this.Invoke("processHSCFile", new object[] {
                        arg0});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginprocessHSCFile(hscFile arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("processHSCFile", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndprocessHSCFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void processHSCFileAsync(hscFile arg0) {
            this.processHSCFileAsync(arg0, null);
        }
        
        /// <remarks/>
        public void processHSCFileAsync(hscFile arg0, object userState) {
            if ((this.processHSCFileOperationCompleted == null)) {
                this.processHSCFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessHSCFileOperationCompleted);
            }
            this.InvokeAsync("processHSCFile", new object[] {
                        arg0}, this.processHSCFileOperationCompleted, userState);
        }
        
        private void OnprocessHSCFileOperationCompleted(object arg) {
            if ((this.processHSCFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processHSCFileCompleted(this, new processHSCFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", ResponseNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile getHSCFile() {
            object[] results = this.Invoke("getHSCFile", new object[0]);
            return ((hscFile)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetHSCFile(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getHSCFile", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public hscFile EndgetHSCFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((hscFile)(results[0]));
        }
        
        /// <remarks/>
        public void getHSCFileAsync() {
            this.getHSCFileAsync(null);
        }
        
        /// <remarks/>
        public void getHSCFileAsync(object userState) {
            if ((this.getHSCFileOperationCompleted == null)) {
                this.getHSCFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetHSCFileOperationCompleted);
            }
            this.InvokeAsync("getHSCFile", new object[0], this.getHSCFileOperationCompleted, userState);
        }
        
        private void OngetHSCFileOperationCompleted(object arg) {
            if ((this.getHSCFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getHSCFileCompleted(this, new getHSCFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", ResponseNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile findHSCFile([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] hscFile arg0) {
            object[] results = this.Invoke("findHSCFile", new object[] {
                        arg0});
            return ((hscFile)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginfindHSCFile(hscFile arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("findHSCFile", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public hscFile EndfindHSCFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((hscFile)(results[0]));
        }
        
        /// <remarks/>
        public void findHSCFileAsync(hscFile arg0) {
            this.findHSCFileAsync(arg0, null);
        }
        
        /// <remarks/>
        public void findHSCFileAsync(hscFile arg0, object userState) {
            if ((this.findHSCFileOperationCompleted == null)) {
                this.findHSCFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindHSCFileOperationCompleted);
            }
            this.InvokeAsync("findHSCFile", new object[] {
                        arg0}, this.findHSCFileOperationCompleted, userState);
        }
        
        private void OnfindHSCFileOperationCompleted(object arg) {
            if ((this.findHSCFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findHSCFileCompleted(this, new findHSCFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", ResponseNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile getFileForProcessing() {
            object[] results = this.Invoke("getFileForProcessing", new object[0]);
            return ((hscFile)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetFileForProcessing(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getFileForProcessing", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public hscFile EndgetFileForProcessing(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((hscFile)(results[0]));
        }
        
        /// <remarks/>
        public void getFileForProcessingAsync() {
            this.getFileForProcessingAsync(null);
        }
        
        /// <remarks/>
        public void getFileForProcessingAsync(object userState) {
            if ((this.getFileForProcessingOperationCompleted == null)) {
                this.getFileForProcessingOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFileForProcessingOperationCompleted);
            }
            this.InvokeAsync("getFileForProcessing", new object[0], this.getFileForProcessingOperationCompleted, userState);
        }
        
        private void OngetFileForProcessingOperationCompleted(object arg) {
            if ((this.getFileForProcessingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFileForProcessingCompleted(this, new getFileForProcessingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", ResponseNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object[] getPacketsForFile([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] hscFile arg0) {
            object[] results = this.Invoke("getPacketsForFile", new object[] {
                        arg0});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPacketsForFile(hscFile arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPacketsForFile", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public object[] EndgetPacketsForFile(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getPacketsForFileAsync(hscFile arg0) {
            this.getPacketsForFileAsync(arg0, null);
        }
        
        /// <remarks/>
        public void getPacketsForFileAsync(hscFile arg0, object userState) {
            if ((this.getPacketsForFileOperationCompleted == null)) {
                this.getPacketsForFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPacketsForFileOperationCompleted);
            }
            this.InvokeAsync("getPacketsForFile", new object[] {
                        arg0}, this.getPacketsForFileOperationCompleted, userState);
        }
        
        private void OngetPacketsForFileOperationCompleted(object arg) {
            if ((this.getPacketsForFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPacketsForFileCompleted(this, new getPacketsForFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", ResponseNamespace="http://adapter.ejb.hsconnect.hs.tdr3.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void markAsProcessed([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] hscFile arg0) {
            this.Invoke("markAsProcessed", new object[] {
                        arg0});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginmarkAsProcessed(hscFile arg0, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("markAsProcessed", new object[] {
                        arg0}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndmarkAsProcessed(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void markAsProcessedAsync(hscFile arg0) {
            this.markAsProcessedAsync(arg0, null);
        }
        
        /// <remarks/>
        public void markAsProcessedAsync(hscFile arg0, object userState) {
            if ((this.markAsProcessedOperationCompleted == null)) {
                this.markAsProcessedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmarkAsProcessedOperationCompleted);
            }
            this.InvokeAsync("markAsProcessed", new object[] {
                        arg0}, this.markAsProcessedOperationCompleted, userState);
        }
        
        private void OnmarkAsProcessedOperationCompleted(object arg) {
            if ((this.markAsProcessedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.markAsProcessedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class hscPacket {
        
        private string binDataField;
        
        private long idField;
        
        private byte[] packetDataField;
        
        private long recordIdField;
        
        private int seqNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string binData {
            get {
                return this.binDataField;
            }
            set {
                this.binDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] packetData {
            get {
                return this.packetDataField;
            }
            set {
                this.packetDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long recordId {
            get {
                return this.recordIdField;
            }
            set {
                this.recordIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int seqNumber {
            get {
                return this.seqNumberField;
            }
            set {
                this.seqNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class operationResponse {
        
        private hscPacket returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscPacket @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class operation {
        
        private hscPacket parameterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscPacket parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class findHSCFileResponse {
        
        private hscFile returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class hscFile {
        
        private bool binCompleteField;
        
        private int clientIDField;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        private bool doProcessField;
        
        private string fileNameField;
        
        private string guidField;
        
        private hscPacket[] hspField;
        
        private long idField;
        
        private bool isFlatField;
        
        private bool isProcessedField;
        
        private System.DateTime lockTimeField;
        
        private bool lockTimeFieldSpecified;
        
        private bool lockedField;
        
        private int processingRefField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool binComplete {
            get {
                return this.binCompleteField;
            }
            set {
                this.binCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int clientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                this.dateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool doProcess {
            get {
                return this.doProcessField;
            }
            set {
                this.doProcessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("hsp", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public hscPacket[] hsp {
            get {
                return this.hspField;
            }
            set {
                this.hspField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isFlat {
            get {
                return this.isFlatField;
            }
            set {
                this.isFlatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isProcessed {
            get {
                return this.isProcessedField;
            }
            set {
                this.isProcessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime lockTime {
            get {
                return this.lockTimeField;
            }
            set {
                this.lockTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lockTimeSpecified {
            get {
                return this.lockTimeFieldSpecified;
            }
            set {
                this.lockTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool locked {
            get {
                return this.lockedField;
            }
            set {
                this.lockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int processingRef {
            get {
                return this.processingRefField;
            }
            set {
                this.processingRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class findHSCFile {
        
        private hscFile arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class persistResponse {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class persist {
        
        private hscFile fileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class getFileForProcessingResponse {
        
        private hscFile returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class getFileForProcessing {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class processHSCFileResponse {
        
        private object returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class processHSCFile {
        
        private hscFile arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class getPacketsForFile {
        
        private hscFile arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class getHSCFileResponse {
        
        private hscFile returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class getHSCFile {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class markAsProcessedResponse {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adapter.ejb.hsconnect.hs.tdr3.com/")]
    public partial class markAsProcessed {
        
        private hscFile arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hscFile arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void operationCompletedEventHandler(object sender, operationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class operationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal operationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public hscPacket Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((hscPacket)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void persistCompletedEventHandler(object sender, persistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class persistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal persistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void processHSCFileCompletedEventHandler(object sender, processHSCFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processHSCFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processHSCFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getHSCFileCompletedEventHandler(object sender, getHSCFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getHSCFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getHSCFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public hscFile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((hscFile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void findHSCFileCompletedEventHandler(object sender, findHSCFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findHSCFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findHSCFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public hscFile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((hscFile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getFileForProcessingCompletedEventHandler(object sender, getFileForProcessingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFileForProcessingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFileForProcessingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public hscFile Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((hscFile)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getPacketsForFileCompletedEventHandler(object sender, getPacketsForFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPacketsForFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPacketsForFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void markAsProcessedCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591